import './globals.css'
import { Barlow,Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const barlow = Barlow({ weight: ['400','500','700'],
subsets: ['latin'] ,variable:'--font-barlow'});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${barlow.variable}`}>{children}</body>
    </html>
  )
}
